services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5050:5050"
    command: sh -c "tsc --watch & npx nodemon /app/dist/server.mjs"
    depends_on:
      - mongo
    env_file:
      - ./.env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
