name: Backend CI

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm i
        working-directory: backend

      - name: Type Check
        run: npm run type-check
        working-directory: backend

      - name: Lint Code
        run: npm run lint
        working-directory: backend

      - name: Run tests
        run: npm test
        working-directory: backend
        env:
          NODE_ENV: "development"
          taskPrompt: ${{ secrets.TASK_PROMPT }}
          openaiApiKey: ${{ secrets.OPENAI_API_KEY }}
          mongoUri: ${{ secrets.MONGO_URI }}
          serviceAccountKey: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          frontendBaseUrl: ${{ secrets.FRONTEND_BASE_URL }}
          frontendDomain: ${{ secrets.FRONTEND_DOMAIN }}
          rolePrompt: ${{ secrets.ROLE_PROMPT }}
